# Generated by Django 4.1.7 on 2023-04-02 06:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0002_rename_products_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="Brand",
            field=models.CharField(default="Marty's Cart", max_length=50),
        ),
    ]
