# Generated by Django 4.1.7 on 2023-04-04 14:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0005_alter_product_product_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_id",
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
